#!/usr/bin/env bash
# Configure my Nginx server so /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://meet.google.com;\n\t}"
sudo sed -i "55i $redirect"  /etc/nginx/sites-available/default

sudo service nginx restart
