#!/usr/bin/env bash
# This script parses the Apache log access file and displays grouped data by IP and HTTP status code.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
