#!/usr/bin/env bash
# Displays "Best School" 10 times, and on the 9th iteration, it displays "Best School" on one line and "Hi" on a new line

count=1
while [ "$count" -le 10 ]; do
    if [ "$count" -eq 9 ]; then
        echo -n "Best School"
        echo " Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
